export const LEGAL_KEYS = {
  VACATION_TIER1_MIN_YEARS: 'VACATION_TIER1_MIN_YEARS',
  VACATION_TIER1_DAYS: 'VACATION_TIER1_DAYS',
  VACATION_TIER2_MIN_YEARS: 'VACATION_TIER2_MIN_YEARS',
  VACATION_TIER2_DAYS: 'VACATION_TIER2_DAYS',
  VACATION_TIER3_MIN_YEARS: 'VACATION_TIER3_MIN_YEARS',
  VACATION_TIER3_DAYS: 'VACATION_TIER3_DAYS',
  VACATION_REQUIRE_HR_APPROVAL: 'VACATION_REQUIRE_HR_APPROVAL',
  VACATION_COUNT_SATURDAY: 'VACATION_COUNT_SATURDAY',
  VACATION_CREDIT_ON_GESTION_START: 'VACATION_CREDIT_ON_GESTION_START',

  LACTATION_DAILY_MINUTES: 'LACTATION_DAILY_MINUTES',
  LACTATION_MONTHS: 'LACTATION_MONTHS',
  JOB_PROTECTION_MONTHS_AFTER_BIRTH: 'JOB_PROTECTION_MONTHS_AFTER_BIRTH',
  LACTATION_ALERT_DAYS: 'LACTATION_ALERT_DAYS',

  AGUINALDO_MIN_MONTHS: 'AGUINALDO_MIN_MONTHS',
  DOUBLE_AGUINALDO: 'DOUBLE_AGUINALDO',

  AFP_EMPLOYEE_RATE: 'AFP_EMPLOYEE_RATE',
  RCIVA_RATE: 'RCIVA_RATE',
  RCIVA_EXEMPT_MINIMUM_WAGES: 'RCIVA_EXEMPT_MINIMUM_WAGES',
  MINIMUM_WAGE: 'MINIMUM_WAGE',

  WORK_HOURS_PER_DAY: 'WORK_HOURS_PER_DAY',
  WORK_HOURS_PER_WEEK: 'WORK_HOURS_PER_WEEK',
  WORK_DAYS_PER_MONTH: 'WORK_DAYS_PER_MONTH',
  OVERTIME_DAY_SURCHARGE: 'OVERTIME_DAY_SURCHARGE',
  OVERTIME_NIGHT_SURCHARGE: 'OVERTIME_NIGHT_SURCHARGE',
  OVERTIME_HOLIDAY_SURCHARGE: 'OVERTIME_HOLIDAY_SURCHARGE',
} as const;

export type LegalKey = (typeof LEGAL_KEYS)[keyof typeof LEGAL_KEYS];
